import os
import datetime
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom import minidom

class RSSAI:
    """
    RSSAI: Responsible for generating and updating the Pinterest RSS feed.
    """
    def __init__(self, feed_title="NexusProfit Deals", feed_link="https://creativeauraland-art.github.io/nexusprofit/"):
        self.feed_title = feed_title
        self.feed_link = feed_link
        self.feed_description = "Curated high-ticket affiliate deals and tools."

    def generate_rss(self, items, output_path="nexusprofit/rss.xml"):
        print(f"[RSSAI] Generating RSS feed with {len(items)} items...")
        
        rss = Element('rss', version='2.0')
        channel = SubElement(rss, 'channel')
        
        SubElement(channel, 'title').text = self.feed_title
        SubElement(channel, 'link').text = self.feed_link
        SubElement(channel, 'description').text = self.feed_description
        
        for item in items:
            rss_item = SubElement(channel, 'item')
            SubElement(rss_item, 'title').text = item['title']
            SubElement(rss_item, 'link').text = item['link']
            SubElement(rss_item, 'description').text = item['description']
            SubElement(rss_item, 'enclosure', url=item['image_url'], type="image/png")
            SubElement(rss_item, 'pubDate').text = datetime.datetime.now().strftime("%a, %d %b %Y %H:%M:%S +0000")
            SubElement(rss_item, 'guid').text = item['link'] + "#" + str(datetime.datetime.now().timestamp())

        # Pretty print
        xml_str = minidom.parseString(tostring(rss)).toprettyxml(indent="   ")
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(xml_str)
        
        return output_path

if __name__ == "__main__":
    rss_ai = RSSAI()
    sample_items = [{
        "title": "Sample Pin",
        "link": "https://creativeauraland-art.github.io/nexusprofit/bridge/index.html",
        "description": "This is a sample pin generated by NexusProfit.",
        "image_url": "https://creativeauraland-art.github.io/nexusprofit/assets/sample_pin.png"
    }]
    rss_ai.generate_rss(sample_items, "rss.xml")
